export const ON_ADD_EMAIL_TO_NEWSLETTER_SUCCEEDED = "ON_ADD_EMAIL_TO_NEWSLETTER_SUCCEEDED";
export const ON_ADD_EMAIL_TO_NEWSLETTER_FAILED = "ON_ADD_EMAIL_TO_NEWSLETTER_FAILED";

export const ON_SUBSCRIBE_STOCKOUT_SUCCEEDED = "ON_SUBSCRIBE_STOCKOUT_SUCCEEDED";
export const ON_SUBSCRIBE_STOCKOUT_FAILED = "ON_SUBSCRIBE_STOCKOUT_FAILED";

export const ON_CLEAN_ERRORS_NEWSLETTER = "ON_CLEAN_ERRORS_NEWSLETTER";
export const ON_CLEAN_ERRORS_STOCKOUT = "ON_CLEAN_ERRORS_STOCKOUT";

export const ON_ADD_EMAIL_TO_CHECKOUT_NEWS_SUCCEEDED = "ON_ADD_EMAIL_TO_CHECKOUT_NEWS_SUCCEEDED";
export const ON_ADD_EMAIL_TO_CHECKOUT_NEWS_FAILED = "ON_ADD_EMAIL_TO_CHECKOUT_NEWS_FAILED";

export const ON_CLEAN_ERRORS_PRE_CYBER = "ON_CLEAN_ERRORS_PRE_CYBER";

export const ON_BIG_BANNER_SUCCEEDED = "ON_BIG_BANNER_SUCCEEDED";
export const ON_BIG_BANNER_FAILED = "ON_BIG_BANNER_FAILED";

export const ON_POPUP_SUCCEEDED = "ON_POPUP_SUCCEEDED";
export const ON_POPUP_FAILED = "ON_POPUP_FAILED";

export const ON_SAVE_ABANDONED_CART_CHECKOUT_SUCCEEDED = "ON_SAVE_ABANDONED_CART_CHECKOUT_SUCCEEDED";
export const ON_SAVE_ABANDONED_CART_CHECKOUT_FAILED = "ON_SAVE_ABANDONED_CART_CHECKOUT_FAILED";

export const ON_GET_ABANDONED_CART_CHECKOUT_SUCCEEDED = "ON_GET_ABANDONED_CART_CHECKOUT_SUCCEEDED";
export const ON_GET_ABANDONED_CART_CHECKOUT_FAILED = "ON_SAGETBANDONED_CART_CHECKOUT_FAILED";