export const ON_GET_PRODUCT_SUCCEEDED = 'ON_GET_PRODUCT_SUCCEEDED';
export const ON_GET_PRODUCT_FAILED = 'ON_GET_PRODUCT_FAILED';

export const ON_GET_HOME_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_HOME_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_HOME_RELATED_PRODUCTS_FAILED = 'ON_GET_HOME_RELATED_PRODUCTS_FAILED';

export const ON_GET_NEW_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_NEW_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_NEW_RELATED_PRODUCTS_FAILED = 'ON_GET_NEW_RELATED_PRODUCTS_FAILED';

export const ON_GET_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_RELATED_PRODUCTS_FAILED = 'ON_GET_RELATED_PRODUCTS_FAILED';

export const ON_GET_DEFAULT_PRODUCTS_SUCCEEDED = 'ON_GET_DEFAULT_PRODUCTS_SUCCEEDED';
export const ON_GET_DEFAULT_PRODUCTS_FAILED = 'ON_GET_DEFAULT_PRODUCTS_FAILED';

export const ON_GET_SHIPPING_TIME_SUCCEEDED = 'ON_GET_SHIPPING_TIME_SUCCEEDED';
export const ON_GET_SHIPPING_TIME_FAILED = 'ON_GET_SHIPPING_TIME_FAILED';

export const ON_GET_HOLIDAYS_SUCCEEDED = 'ON_GET_HOLIDAYS_SUCCEEDED';
export const ON_GET_HOLIDAYS_FAILED = 'ON_GET_HOLIDAYS_FAILED';

export const ON_GET_STOCK_SUCCEEDED = 'ON_GET_STOCK_SUCCEEDED';
export const ON_GET_STOCK_FAILED = 'ON_GET_STOCK_FAILED';

export const ON_GET_STOCK_AND_PRICES_SUCCEEDED = 'ON_GET_STOCK_AND_PRICES_SUCCEEDED';
export const ON_GET_STOCK_AND_PRICES_FAILED = 'ON_GET_STOCK_AND_PRICES_FAILED';

export const ON_OPEN_QUIZZ_SUCCEEDED = 'ON_OPEN_QUIZZ_SUCCEEDED';
export const ON_CLOSE_QUIZZ_FAILED = 'ON_CLOSE_QUIZZ_FAILED';

export const ON_GET_UNAVAILABLE_DAYS_SUCCEEDED = "ON_GET_UNAVAILABLE_DAYS_SUCCEEDED"
export const ON_GET_UNAVAILABLE_DAYS_FAILED = "ON_GET_UNAVAILABLE_DAYS_FAILED"

export const ON_GET_NUEVOS_DISENOS_SUCCEEDED = 'ON_GET_NUEVOS_DISENOS_SUCCEEDED';
export const ON_GET_NUEVOS_DISENOS_FAILED = 'ON_GET_NUEVOS_DISENOS_FAILED';

export const ON_GET_OPEN_OVERLAY = 'ON_GET_OPEN_OVERLAY';
export const ON_GET_CLOSE_OVERLAY = 'ON_GET_CLOSE_OVERLAY';


export const ON_GET_SHOW_NAVBAR = 'ON_GET_SHOW_NAVBAR';
export const ON_GET_HIDE_NAVBAR = 'ON_GET_HIDE_NAVBAR';