export const ON_GET_ORDER_SUCCEEDED = "ON_GET_ORDER_SUCCEEDED";
export const ON_GET_ORDER_FAILED = "ON_GET_ORDER_FAILED";
export const ON_GET_SEGUIMIENTO_SUCCEEDED = "ON_GET_SEGUIMIENTO_SUCCEDED";
export const ON_GET_SEGUIMIENTO_FAILED = "ON_GET_SEGUIMIENTO_FAILED";

export const ON_GET_CARD_INFO_SUCCEEDED = "ON_GET_CARD_INFO_SUCCEEDED";
export const ON_GET_CARD_INFO_FAILED = "ON_GET_CARD_INFO_FAILED";

export const ON_SEND_ORDER_DATA_SUCCEEDED = "ON_SEND_ORDER_DATA_SUCCEEDED";
export const ON_SEND_ORDER_DATA_FAILED = "ON_SEND_ORDER_DATA_FAILED";

export const ON_GET_TOKEN_SUCCEEDED = "ON_GET_TOKEN_SUCCEEDED";
export const ON_GET_TOKEN_FAILED = "ON_GET_TOKEN_FAILED";
export const ON_GET_CPFLOTA_SUCCEEDED = "ON_GET_CPFLOTA_SUCCEEDED";
export const ON_GET_CPFLOTA_FAILED = "ON_GET_CPFLOTA_FAILED";

export const ON_GET_DELIVERY_TIMES_SUCCEEDED = "ON_GET_DELIVERY_TIMES_SUCCEEDED";
export const ON_GET_DELIVERY_TIMES_FAILED = "ON_GET_DELIVERY_TIMES_FAILED";

export const ON_VERIFY_ORDER_EXIST_SUCCEEDED="ON_VERIFY_ORDER_EXIST_SUCCEEDED";
export const ON_VERIFY_ORDER_EXIST_FAILED="ON_VERIFY_ORDER_EXIST_FAILED";

export const ON_CLEAN_ORDER_EXISTS="ON_CLEAN_ORDER_EXISTS";

export const ON_SET_CHECKOUT_ONLY_TO_PAY="ON_SET_CHECKOUT_ONLY_TO_PAY";
export const ON_SEND_CLEAR_ERROR="ON_SEND_CLEAR_ERROR";

export const ON_GET_RDC_SUCCEEDED="ON_GET_RDC_SUCCEEDED";
export const ON_GET_RDC_FAILED="ON_GET_RDC_FAILED";

export const ON_GET_FORGOTTEN_EMAIL_SUCCEEDED="ON_GET_FORGOTTEN_EMAIL_SUCCEEDED";
export const ON_GET_FORGOTTEN_EMAIL_FAILED="ON_GET_FORGOTTEN_EMAIL_FAILED";

export const ON_GET_PUBLIC_IP_SUCCEEDED="ON_GET_PUBLIC_IP_SUCCEEDED";
export const ON_GET_PUBLIC_IP_FAILED="ON_GET_PUBLIC_IP_FAILED";

export const ON_DEFINE_CHECKOUT_PATH_SUCCEEDED="ON_DEFINE_CHECKOUT_PATH_SUCCEEDED";

export const ON_GET_CPCABA_SUCCEEDED = "ON_GET_CPCABA_SUCCEEDED";
export const ON_GET_CPCABA_FAILED = "ON_GET_CPCABA_FAILED";