export const ON_SAVE_HYGRAPH_COMPONENT = "ON_SAVE_HYGRAPH_COMPONENT";

export const ON_GET_HOME_HYGRAPH_DATA_SUCCEEDED = "ON_GET_HOME_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_HOME_HYGRAPH_DATA_FAILED = "ON_GET_HOME_HYGRAPH_DATA_FAILED";

export const ON_GET_PILLS_HYGRAPH_DATA_SUCCEEDED = "ON_GET_PILLS_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_PILLS_HYGRAPH_DATA_FAILED = "ON_GET_PILLS_HYGRAPH_DATA_FAILED";

export const ON_GET_HEAD_BANNERS_HYGRAPH_DATA_SUCCEEDED = "ON_GET_HEAD_BANNERS_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_HEAD_BANNERS_HYGRAPH_DATA_FAILED = "ON_GET_HEAD_BANNERS_HYGRAPH_DATA_FAILED";

export const ON_GET_PL_SEO_HYGRAPH_DATA_SUCCEEDED = "ON_GET_PL_SEO_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_PL_SEO_HYGRAPH_DATA_FAILED = "ON_GET_PL_SEO_HYGRAPH_DATA_FAILED";

export const ON_GET_STATIC_SEO_HYGRAPH_DATA_SUCCEEDED = "ON_GET_STATIC_SEO_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_STATIC_SEO_HYGRAPH_DATA_FAILED = "ON_GET_STATIC_SEO_HYGRAPH_DATA_FAILED";

export const ON_GET_SIDECART_HYGRAPH_DATA_SUCCEEDED = "ON_GET_SIDECART_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_SIDECART_HYGRAPH_DATA_FAILED = "ON_GET_SIDECART_HYGRAPH_DATA_FAILED";

export const ON_GET_TYC_HYGRAPH_DATA_SUCCEEDED = "ON_GET_TYC_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_TYC_HYGRAPH_DATA_FAILED = "ON_GET_TYC_HYGRAPH_DATA_FAILED";

export const ON_GET_TYC_PROMO_HYGRAPH_DATA_SUCCEEDED = "ON_GET_TYC_PROMO_HYGRAPH_DATA_SUCCEEDED";
export const ON_GET_TYC_PROMO_HYGRAPH_DATA_FAILED = "ON_GET_TYC_PROMO_HYGRAPH_DATA_FAILED";

export const ON_GET_POPUP_SUCCEEDED = "ON_GET_POPUP_SUCCEEDED";
export const ON_GET_POPUP_FAILED = "ON_GET_POPUP_FAILED";

export const ON_GET_BANNER_AND_CUCARDA_SUCCEEDED = "ON_GET_BANNER_AND_CUCARDA_SUCCEEDED";
export const ON_GET_BANNER_AND_CUCARDA__FAILED = "ON_GET_BANNER_AND_CUCARDA__FAILED";

export const ON_GET_BIG_BANNERS_SUCCEEDED = "ON_GET_BIG_BANNERS_SUCCEEDED";
export const ON_GET_BIG_BANNERS_FAILED = "ON_GET_BIG_BANNERS_FAILED";

export const ON_GET_CLEAR_CACHE_SUCCEEDED = "ON_GET_CLEAR_CACHE_SUCCEEDED";
export const ON_GET_CLEAR_CACHE_FAILED = "ON_GET_CLEAR_CACHE_FAILED";