export const ON_GET_USER_IS_LOGGED_SUCCEEDED = "ON_GET_USER_IS_LOGGED_SUCCEEDED"
export const ON_GET_USER_IS_LOGGED_FAILED = "ON_GET_USER_IS_LOGGED_FAILED"

export const ON_GET_OPEN_CHECKOUT_CHAT_SUCCEEDED = "ON_GET_OPEN_CHECKOUT_CHAT_SUCCEEDED"

export const ON_ENTER_CP = "ON_ENTER_CP"