export const ON_GET_CART_SUCCEEDED = 'ON_GET_CART_SUCCEEDED';
export const ON_GET_CART_FAILED = 'ON_GET_CART_FAILED';

export const ON_GET_VARIATION_SUCCEEDED = 'ON_GET_VARIATION_SUCCEEDED';
export const ON_GET_VARIATION_FAILED = 'ON_GET_VARIATION_FAILED';

export const ON_ADD_ITEM_TO_CART_SUCCEEDED = 'ON_ADD_ITEM_TO_CART_SUCCEEDED';
export const ON_ADD_ITEM_TO_CART_FAILED = 'ON_ADD_ITEM_TO_CART_FAILED';

export const ON_REMOVE_ITEM_FROM_CART_SUCCEEDED = 'ON_REMOVE_ITEM_FROM_CART_SUCCEEDED';
export const ON_REMOVE_ITEM_FROM_CART_FAILED = 'ON_REMOVE_ITEM_FROM_CART_FAILED';

export const ON_UPDATE_ITEM_FROM_CART_SUCCEEDED = 'ON_UPDATE_ITEM_FROM_CART_SUCCEEDED';
export const ON_UPDATE_ITEM_FROM_CART_FAILED = 'ON_UPDATE_ITEM_FROM_CART_FAILED';

export const ON_ADD_COUPON_TO_CART_SUCCEEDED = "ON_ADD_COUPON_TO_CART_SUCCEEDED";
export const ON_ADD_COUPON_TO_CART_FAILED = "ON_ADD_COUPON_TO_CART_FAILED";

export const ON_CLEAR_CART_SUCCEEDED = "ON_CLEAR_CART_SUCCEEDED";
export const ON_CLEAR_CART_FAILED = "ON_CLEAR_CART_FAILED";

export const ON_REMOVE_COUPON_TO_CART_SUCCEEDED = "ON_REMOVE_COUPON_TO_CART_SUCCEEDED";
export const ON_REMOVE_COUPON_TO_CART_FAILED = "ON_REMOVE_COUPON_TO_CART_FAILED";

export const ON_UPDATE_SHIPPING_FROM_CART_SUCCEEDED = "ON_UPDATE_SHIPPING_FROM_CART_SUCCEEDED";
export const ON_UPDATE_SHIPPING_FROM_CART_FAILED = "ON_UPDATE_SHIPPING_FROM_CART_FAILED";

export const ON_GET_CART_RELATED_PRODUCTS_SUCCEEDED = 'ON_GET_CART_RELATED_PRODUCTS_SUCCEEDED';
export const ON_GET_CART_RELATED_PRODUCTS_FAILED = 'ON_GET_CART_RELATED_PRODUCTS_FAILED';

export const ON_OPEN_SIDECART = 'ON_OPEN_SIDECART';
export const ON_CLOSE_SIDECART = 'ON_CLOSE_SIDECART';

export const ON_UPDATE_CART_DATA_WITH_SESSION = 'ON_UPDATE_CART_DATA_WITH_SESSION';

export const ON_SHOW_FIXEDCART = 'ON_SHOW_FIXEDCART';
export const ON_CLOSE_FIXEDCART = 'ON_CLOSE_FIXEDCART';

export const ON_VISIBLE_FIXEDCART = 'ON_VISIBLE_FIXEDCART';
export const ON_NOTVISIBLE_FIXEDCART = 'ON_NOTVISIBLE_FIXEDCART';

export const ON_MOBILE_MENU_OPEN = 'ON_MOBILE_MENU_OPEN';
export const ON_MOBILE_MENU_CLOSE = 'ON_MOBILE_MENU_CLOSE';